name: todo-list
services:
    mysql:
        container_name: mysql
        image: mysql:8.0
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_USER: integradora
            MYSQL_PASSWORD: integradora
            MYSQL_ROOT_PASSWORD: integradora
            MYSQL_DATABASE: todos

    docker-integradora:
        image: malpeliluis/docker-integradora
        ports:
            - 8080:3000
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: integradora
            MYSQL_PASSWORD: integradora
            MYSQL_DB: todos
        depends_on: 
           - mysql
        restart: always
networks:
    red-integradora:
        name: red-integradora
volumes:
    data:
        name: data